/* Name: Harshita Aka Dharna Mistry
 * Name : Sheenam Kamal
 * Name : Kour Sanminder
 * JavaProject
 *
 * description:A java GUI application that if customer chooses cash option than 
 * by entering bill amt and amt given by customer we can identify change.
 */

package javaproject;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class CashOption extends javax.swing.JFrame {

    /**
     * Creates new form CashOption
     */
    public CashOption() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cashTextField = new javax.swing.JTextField();
        billTextField = new javax.swing.JTextField();
        changeTextField = new javax.swing.JTextField();
        doneButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        signInMenuItem = new javax.swing.JMenuItem();
        pickUpItem = new javax.swing.JMenuItem();
        registerMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(500, 500));
        setMinimumSize(new java.awt.Dimension(500, 500));
        setPreferredSize(new java.awt.Dimension(500, 500));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 255));
        jLabel1.setText("Cash Given");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 110, 100, 17);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 255));
        jLabel2.setText("Bill Amount");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 170, 90, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 255));
        jLabel3.setText("Change");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 240, 70, 17);

        cashTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(cashTextField);
        cashTextField.setBounds(220, 110, 170, 40);
        getContentPane().add(billTextField);
        billTextField.setBounds(220, 170, 170, 40);
        getContentPane().add(changeTextField);
        changeTextField.setBounds(220, 230, 170, 40);

        doneButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        doneButton.setForeground(new java.awt.Color(0, 153, 153));
        doneButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/_images/proceed.jpg"))); // NOI18N
        doneButton.setText("Done");
        doneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneButtonActionPerformed(evt);
            }
        });
        getContentPane().add(doneButton);
        doneButton.setBounds(170, 320, 110, 50);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 153));
        jLabel5.setText("ZOOM DRY CLEANING");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(160, 60, 199, 22);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/_images/background.jpg"))); // NOI18N
        jLabel4.setMaximumSize(new java.awt.Dimension(500, 500));
        jLabel4.setMinimumSize(new java.awt.Dimension(500, 500));
        jLabel4.setPreferredSize(new java.awt.Dimension(500, 500));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 500, 500);

        jMenu3.setText("Menu");

        signInMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/_images/signInsmall.jpg"))); // NOI18N
        signInMenuItem.setText("Signin");
        signInMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInMenuItemActionPerformed(evt);
            }
        });
        jMenu3.add(signInMenuItem);

        pickUpItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/_images/pickUpSmall.jpg"))); // NOI18N
        pickUpItem.setText("Pick Up");
        pickUpItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pickUpItemActionPerformed(evt);
            }
        });
        jMenu3.add(pickUpItem);

        registerMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/_images/registerSmall.png"))); // NOI18N
        registerMenuItem.setText("Register");
        registerMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerMenuItemActionPerformed(evt);
            }
        });
        jMenu3.add(registerMenuItem);

        jMenuBar2.add(jMenu3);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cashTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cashTextFieldActionPerformed

    private void doneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneButtonActionPerformed
        double cash = Double.parseDouble(cashTextField.getText());
        double bill = Double.parseDouble(billTextField.getText());
        double change;
        if(cash>bill)
        {
            change = cash-bill;
        }
        else
        {
            change = bill-cash;
        }
        double ch = Double.parseDouble(new DecimalFormat("##.##").format(change));
        changeTextField.setText(Double.toString(ch));
        JOptionPane.showMessageDialog(null, "Thank you come again :) ", "Greetings", JOptionPane.INFORMATION_MESSAGE);
        this.setVisible(false);
    }//GEN-LAST:event_doneButtonActionPerformed

    private void signInMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInMenuItemActionPerformed
        signIn s = new signIn();
        s.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_signInMenuItemActionPerformed

    private void pickUpItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pickUpItemActionPerformed
        PickUp p = new PickUp();
       p.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_pickUpItemActionPerformed

    private void registerMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerMenuItemActionPerformed
         Register r = new Register();
        r.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_registerMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CashOption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CashOption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CashOption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CashOption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CashOption().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField billTextField;
    private javax.swing.JTextField cashTextField;
    private javax.swing.JTextField changeTextField;
    private javax.swing.JButton doneButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem pickUpItem;
    private javax.swing.JMenuItem registerMenuItem;
    private javax.swing.JMenuItem signInMenuItem;
    // End of variables declaration//GEN-END:variables
public void setTextBoxText(String sett)
{
    billTextField.setText(sett);
}
}
