/* Name: Harshita Aka Dharna Mistry
 * Name : Sheenam Kamal
 * Name : Kour Sanminder
 * JavaProject
 *
 * description:A java GUI application to Display orders. User have to select 
 * on any order 
 * and it will show prices along with that order.
 */

package javaproject;

import java.io.IOException;
import java.util.TreeSet;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ListModel;

/**
 *
 * @author admin
 */
public class DisplayOrders extends javax.swing.JFrame{
    double orderBill=0;
    double HST=0;
    double finalBill=0;
    int count1=0,count2=0,count3=0;
    int count4=0,count5=0,count6=0;
    int count7=0,count8=0,count9=0;
    int count10=0,count11=0,count12=0;
    int count13=0,count14=0,count15=0,count16=0;
    String a,b,c,d,e,r,g,h,i,j,k,l,m,n,o,q;

    /**
     * Creates new form DisplayOrders
     */
    public DisplayOrders() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        itemList = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        smallPantbtn = new javax.swing.JButton();
        mediumPantBtn = new javax.swing.JButton();
        largePantBtn = new javax.swing.JButton();
        smallShirtBtn = new javax.swing.JButton();
        small2pcBtn = new javax.swing.JButton();
        mediumShirtBtn = new javax.swing.JButton();
        largeShirtBtn = new javax.swing.JButton();
        lightDressBtn = new javax.swing.JButton();
        mediumDressBtn = new javax.swing.JButton();
        heavyDressBtn = new javax.swing.JButton();
        simpleCoatBtn = new javax.swing.JButton();
        mediumCoatBtn = new javax.swing.JButton();
        heavyCoatBtn = new javax.swing.JButton();
        smallTieBtn = new javax.swing.JButton();
        large2PcBtn = new javax.swing.JButton();
        largeTieBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        doneBtn = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        signInMenuItem = new javax.swing.JMenuItem();
        pickUpMenuItem = new javax.swing.JMenuItem();
        registerMeniItem = new javax.swing.JMenuItem();

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(500, 500));
        setMinimumSize(new java.awt.Dimension(500, 500));
        setPreferredSize(new java.awt.Dimension(500, 500));
        setResizable(false);
        getContentPane().setLayout(null);

        jScrollPane2.setViewportView(itemList);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(50, 40, 440, 160);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 255));
        jLabel1.setText("Pants");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 210, 39, 17);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 255));
        jLabel2.setText("Shirts");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(230, 210, 50, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 255));
        jLabel3.setText("Dresses");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(340, 210, 53, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 255));
        jLabel4.setText("Tie");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(220, 360, 40, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 255));
        jLabel5.setText("Winter Coat");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 350, 83, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 255));
        jLabel6.setText("2 Piece");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(330, 360, 48, 20);

        smallPantbtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        smallPantbtn.setForeground(new java.awt.Color(0, 153, 153));
        smallPantbtn.setText("Small Pant");
        smallPantbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smallPantbtnActionPerformed(evt);
            }
        });
        getContentPane().add(smallPantbtn);
        smallPantbtn.setBounds(70, 240, 110, 23);

        mediumPantBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mediumPantBtn.setForeground(new java.awt.Color(0, 153, 153));
        mediumPantBtn.setText("Medium Pant");
        mediumPantBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mediumPantBtnActionPerformed(evt);
            }
        });
        getContentPane().add(mediumPantBtn);
        mediumPantBtn.setBounds(70, 270, 113, 23);

        largePantBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        largePantBtn.setForeground(new java.awt.Color(0, 153, 153));
        largePantBtn.setText("Large Pant");
        largePantBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                largePantBtnActionPerformed(evt);
            }
        });
        getContentPane().add(largePantBtn);
        largePantBtn.setBounds(70, 300, 110, 23);

        smallShirtBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        smallShirtBtn.setForeground(new java.awt.Color(0, 153, 153));
        smallShirtBtn.setText("Small Shirt");
        smallShirtBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smallShirtBtnActionPerformed(evt);
            }
        });
        getContentPane().add(smallShirtBtn);
        smallShirtBtn.setBounds(220, 240, 100, 23);

        small2pcBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        small2pcBtn.setForeground(new java.awt.Color(0, 153, 153));
        small2pcBtn.setText("Small");
        small2pcBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                small2pcBtnActionPerformed(evt);
            }
        });
        getContentPane().add(small2pcBtn);
        small2pcBtn.setBounds(320, 390, 65, 23);

        mediumShirtBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mediumShirtBtn.setForeground(new java.awt.Color(0, 153, 153));
        mediumShirtBtn.setText("Medium Shirt");
        mediumShirtBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mediumShirtBtnActionPerformed(evt);
            }
        });
        getContentPane().add(mediumShirtBtn);
        mediumShirtBtn.setBounds(210, 270, 120, 23);

        largeShirtBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        largeShirtBtn.setForeground(new java.awt.Color(0, 153, 153));
        largeShirtBtn.setText("Large Shirt");
        largeShirtBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                largeShirtBtnActionPerformed(evt);
            }
        });
        getContentPane().add(largeShirtBtn);
        largeShirtBtn.setBounds(220, 300, 100, 23);

        lightDressBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lightDressBtn.setForeground(new java.awt.Color(0, 153, 153));
        lightDressBtn.setText("Light");
        lightDressBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lightDressBtnActionPerformed(evt);
            }
        });
        getContentPane().add(lightDressBtn);
        lightDressBtn.setBounds(350, 240, 65, 23);

        mediumDressBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mediumDressBtn.setForeground(new java.awt.Color(0, 153, 153));
        mediumDressBtn.setText("Medium");
        mediumDressBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mediumDressBtnActionPerformed(evt);
            }
        });
        getContentPane().add(mediumDressBtn);
        mediumDressBtn.setBounds(340, 270, 90, 23);

        heavyDressBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        heavyDressBtn.setForeground(new java.awt.Color(0, 153, 153));
        heavyDressBtn.setText("Heavy");
        heavyDressBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heavyDressBtnActionPerformed(evt);
            }
        });
        getContentPane().add(heavyDressBtn);
        heavyDressBtn.setBounds(350, 300, 69, 23);

        simpleCoatBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        simpleCoatBtn.setForeground(new java.awt.Color(0, 153, 153));
        simpleCoatBtn.setText("Simple");
        simpleCoatBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpleCoatBtnActionPerformed(evt);
            }
        });
        getContentPane().add(simpleCoatBtn);
        simpleCoatBtn.setBounds(60, 370, 80, 23);

        mediumCoatBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mediumCoatBtn.setForeground(new java.awt.Color(0, 153, 153));
        mediumCoatBtn.setText("Medium");
        mediumCoatBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mediumCoatBtnActionPerformed(evt);
            }
        });
        getContentPane().add(mediumCoatBtn);
        mediumCoatBtn.setBounds(60, 400, 81, 23);

        heavyCoatBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        heavyCoatBtn.setForeground(new java.awt.Color(0, 153, 153));
        heavyCoatBtn.setText("Heavy");
        heavyCoatBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heavyCoatBtnActionPerformed(evt);
            }
        });
        getContentPane().add(heavyCoatBtn);
        heavyCoatBtn.setBounds(60, 430, 69, 23);

        smallTieBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        smallTieBtn.setForeground(new java.awt.Color(0, 153, 153));
        smallTieBtn.setText("Small Tie");
        smallTieBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smallTieBtnActionPerformed(evt);
            }
        });
        getContentPane().add(smallTieBtn);
        smallTieBtn.setBounds(190, 390, 90, 23);

        large2PcBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        large2PcBtn.setForeground(new java.awt.Color(0, 153, 153));
        large2PcBtn.setText("Large");
        large2PcBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                large2PcBtnActionPerformed(evt);
            }
        });
        getContentPane().add(large2PcBtn);
        large2PcBtn.setBounds(320, 420, 67, 23);

        largeTieBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        largeTieBtn.setForeground(new java.awt.Color(0, 153, 153));
        largeTieBtn.setText("Large Tie");
        largeTieBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                largeTieBtnActionPerformed(evt);
            }
        });
        getContentPane().add(largeTieBtn);
        largeTieBtn.setBounds(190, 430, 90, 23);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(50, 350, 100, 110);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(310, 350, 110, 100);

        doneBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        doneBtn.setForeground(new java.awt.Color(0, 153, 153));
        doneBtn.setText("Done");
        doneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneBtnActionPerformed(evt);
            }
        });
        getContentPane().add(doneBtn);
        doneBtn.setBounds(420, 420, 65, 23);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(180, 350, 100, 110);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/_images/background.jpg"))); // NOI18N
        jLabel7.setMaximumSize(new java.awt.Dimension(500, 500));
        jLabel7.setMinimumSize(new java.awt.Dimension(500, 500));
        jLabel7.setPreferredSize(new java.awt.Dimension(500, 500));
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, -100, 590, 650);
        getContentPane().add(jSeparator4);
        jSeparator4.setBounds(50, 350, 100, 110);
        getContentPane().add(jSeparator5);
        jSeparator5.setBounds(170, 340, 100, 110);

        jMenu1.setText("Menu");

        signInMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/_images/signInsmall.jpg"))); // NOI18N
        signInMenuItem.setText("Signin");
        signInMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(signInMenuItem);

        pickUpMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/_images/pickUpSmall.jpg"))); // NOI18N
        pickUpMenuItem.setText("Pick Up");
        pickUpMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pickUpMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(pickUpMenuItem);

        registerMeniItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/_images/registerSmall.png"))); // NOI18N
        registerMeniItem.setText("Register");
        registerMeniItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerMeniItemActionPerformed(evt);
            }
        });
        jMenu1.add(registerMeniItem);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void largeShirtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_largeShirtBtnActionPerformed
        Prices p = new Prices();
        addItems("Large Shirt : "+p.getLargeShirt());
        orderBill=orderBill+p.getLargeShirt();
        count1++;
        if(count1>0)
        {
             a = "Large Shirt "+p.getLargeShirt();
        }
            
        
    }//GEN-LAST:event_largeShirtBtnActionPerformed

    private void mediumDressBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mediumDressBtnActionPerformed
        Prices p = new Prices();
        addItems("Medium work Dress : "+p.getMediumDress());
        orderBill=orderBill+p.getMediumDress();
        count2++;
        if(count2>0)
        {
             b = "Medium work dress "+p.getMediumDress();
        }
    }//GEN-LAST:event_mediumDressBtnActionPerformed

    private void smallPantbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smallPantbtnActionPerformed
        Prices p = new Prices();
        addItems("Small Pant : "+p.getSmallPant());
        orderBill=orderBill+p.getSmallPant();
        count3++;
        if(count3>0)
        {
             c = "Small Pant "+p.getSmallPant();
        }
    }//GEN-LAST:event_smallPantbtnActionPerformed

    private void mediumPantBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mediumPantBtnActionPerformed
        Prices p = new Prices();
        addItems("Medium Pant : "+p.getMediumPant());
        orderBill=orderBill+p.getMediumPant();
        count4++;
        if(count4>0)
        {
             d = "Medium pant "+p.getMediumPant();
        }
    }//GEN-LAST:event_mediumPantBtnActionPerformed

    private void largePantBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_largePantBtnActionPerformed
        Prices p = new Prices();
        addItems("Large Pant : "+p.getLargePant());
        orderBill=orderBill+p.getLargePant();
        count5++;
        if(count5>0)
        {
             e = "Large Pant  "+p.getMediumDress();
        }
    }//GEN-LAST:event_largePantBtnActionPerformed

    private void smallShirtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smallShirtBtnActionPerformed
        Prices p = new Prices();
        addItems("Small Shirt : "+p.getSmallShirt());
        orderBill=orderBill+p.getSmallShirt();
        count6++;
        if(count6>0)
        {
             r = "Small Shirt"+p.getSmallShirt();
        }
    }//GEN-LAST:event_smallShirtBtnActionPerformed

    private void mediumShirtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mediumShirtBtnActionPerformed
        Prices p = new Prices();
        addItems("Medium Shirt : "+p.getMediumShirt());
        orderBill=orderBill+p.getMediumShirt();
        count7++;
        if(count7>0)
        {
             g = "Medium shirt "+p.getMediumShirt();
        }
    }//GEN-LAST:event_mediumShirtBtnActionPerformed

    private void lightDressBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lightDressBtnActionPerformed
        Prices p = new Prices();
        addItems("Light Work Dress : "+p.getSimpleDress());
        orderBill=orderBill+p.getSimpleDress();
        count8++;
        if(count8>0)
        {
             h = "Light Work Dress "+p.getSimpleDress();
        }
    }//GEN-LAST:event_lightDressBtnActionPerformed

    private void heavyDressBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heavyDressBtnActionPerformed
        Prices p = new Prices();
        addItems("Heavy Work Dress : "+p.getHeavyDress());
        orderBill=orderBill+p.getHeavyDress();
        count9++;
        if(count9>0)
        {
             i = "Heavy Work Dress "+p.getHeavyDress();
        }
    }//GEN-LAST:event_heavyDressBtnActionPerformed

    private void simpleCoatBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpleCoatBtnActionPerformed
        Prices p = new Prices();
        addItems("Simple Winter Coat : "+p.getSimpleCoat());
        orderBill=orderBill+p.getSimpleCoat();
        count10++;
        if(count10>0)
        {
             j = "Simple Winter Coat "+p.getSimpleCoat();
        }
    }//GEN-LAST:event_simpleCoatBtnActionPerformed

    private void mediumCoatBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mediumCoatBtnActionPerformed
       Prices p = new Prices();
       addItems("Medium Winter Coat : "+p.getMediumCoat());
       orderBill=orderBill+p.getMediumCoat();
       count11++;
        if(count11>0)
        {
             k = "Medium Winter Coat "+p.getMediumCoat();
        }
    }//GEN-LAST:event_mediumCoatBtnActionPerformed

    private void heavyCoatBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heavyCoatBtnActionPerformed
        Prices p = new Prices();
        addItems("Heavy Winter Coat : "+p.getHeavyCoat());
        orderBill=orderBill+p.getHeavyCoat();
        count12++;
        if(count12>0)
        {
             l = "Heavy Winter Coat "+p.getHeavyCoat();
        }
    }//GEN-LAST:event_heavyCoatBtnActionPerformed

    private void smallTieBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smallTieBtnActionPerformed
        Prices p = new Prices();
        addItems("Small Tie : "+p.getSmallTie());
        orderBill=orderBill+p.getSmallTie();
        count13++;
        if(count13>0)
        {
             m = "Small Tie "+p.getSmallTie();
        }
    }//GEN-LAST:event_smallTieBtnActionPerformed

    private void largeTieBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_largeTieBtnActionPerformed
        Prices p = new Prices();
        addItems("Large Tie : "+p.getLargeTie());
        orderBill=orderBill+p.getLargeTie();
        count14++;
        if(count14>0)
        {
          n = "Large Tie "+p.getLargeTie();
        }
    }//GEN-LAST:event_largeTieBtnActionPerformed

    private void small2pcBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_small2pcBtnActionPerformed
        Prices p = new Prices();
        addItems("Small 2 Piece : "+p.getSmallTwopc());
        orderBill=orderBill+p.getSmallTwopc();
        count15++;
        if(count15>0)
        {
           o = "Small 2 Piece "+p.getSmallTwopc();
        }
    }//GEN-LAST:event_small2pcBtnActionPerformed

    private void large2PcBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_large2PcBtnActionPerformed
        Prices p = new Prices();
        addItems("Large 2 Piece : "+p.getLargeTwopc());
        orderBill=orderBill+p.getLargeTwopc();
        count16++;
        if(count16>0)
        {
            q = "Large 2 Piece "+p.getLargeTwopc();
        }
    }//GEN-LAST:event_large2PcBtnActionPerformed

    private void doneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneBtnActionPerformed
        
        HST = (orderBill*13)/100;
        finalBill = HST+orderBill;
        addItems("Final Bill is : "+finalBill);
        Functionality f = new Functionality();
        try {
            f.storePhoneNumbers(Double.toString(finalBill));
        } catch (IOException ex) {
            Logger.getLogger(DisplayOrders.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
       /* Payment co = new Payment();
        co.setVisible(true);*/
        BillDisplay bd = new BillDisplay();
        if(count1>0)
        {
           bd.changeText(a+"\n");
        }
        if(count2>0)
        {
            bd.changeText(b+"\n");
        }
        if(count3>0)
        {
            bd.changeText(c+"\n");
        }
        if(count4>0)
        {
            bd.changeText(d+"\n");
        }
        if(count5>0)
        {
            bd.changeText(e+"\n");
        }
        if(count6>0)
        {
            bd.changeText(r+"\n");
        }
        if(count7>0)
        {
            bd.changeText(g+"\n");
        }
        if(count8>0)
        {
            bd.changeText(h+"\n");
        }
        if(count9>0)
        {
            bd.changeText(i+"\n");
        }
        if(count10>0)
        {
            bd.changeText(j+"\n");
        }
        if(count11>0)
        {
            bd.changeText(k+"\n");
        }
        if(count12>0)
        {
            bd.changeText(l+"\n");
        }
        if(count13>0)
        {
            bd.changeText(m+"\n");
        }
        if(count14>0)
        {
            bd.changeText(n+"\n");
        }
        if(count15>0)
        {
            bd.changeText(o+"\n");
        }
        if(count16>0)
        {
            bd.changeText(q+"\n");
        }
        bd.changeText("------------------\n");
        bd.changeText("Total Bill: "+Double.toString(finalBill));
        bd.setVisible(true);
        CashOption cot = new CashOption();
        cot.setTextBoxText(Double.toString(finalBill));
    }//GEN-LAST:event_doneBtnActionPerformed

    private void signInMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInMenuItemActionPerformed
       signIn s = new signIn();
        s.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_signInMenuItemActionPerformed

    private void pickUpMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pickUpMenuItemActionPerformed
        PickUp p = new PickUp();
       p.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_pickUpMenuItemActionPerformed

    private void registerMeniItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerMeniItemActionPerformed
        Register r = new Register();
        r.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_registerMeniItemActionPerformed

    
    public void addItems(String dryCleanItem)
    {
        
       TreeSet<String> listItems = new TreeSet();
        ListModel lmItems = itemList.getModel();
         
        for(int i = 0; i < lmItems.getSize(); i++)
        {
            listItems.add(lmItems.getElementAt(i).toString());
        }
        listItems.add(dryCleanItem);
        DefaultListModel newItems = new DefaultListModel();
        
        while(!listItems.isEmpty())
        {
            
            newItems.addElement(listItems.pollFirst());
        }
        itemList.setModel(newItems);
       
    }
    
    
    
    public void clearList()
    {
        
        
    }    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisplayOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisplayOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisplayOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisplayOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DisplayOrders().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton doneBtn;
    private javax.swing.JButton heavyCoatBtn;
    private javax.swing.JButton heavyDressBtn;
    private javax.swing.JList itemList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList jList1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JButton large2PcBtn;
    private javax.swing.JButton largePantBtn;
    private javax.swing.JButton largeShirtBtn;
    private javax.swing.JButton largeTieBtn;
    private javax.swing.JButton lightDressBtn;
    private javax.swing.JButton mediumCoatBtn;
    private javax.swing.JButton mediumDressBtn;
    private javax.swing.JButton mediumPantBtn;
    private javax.swing.JButton mediumShirtBtn;
    private javax.swing.JMenuItem pickUpMenuItem;
    private javax.swing.JMenuItem registerMeniItem;
    private javax.swing.JMenuItem signInMenuItem;
    private javax.swing.JButton simpleCoatBtn;
    private javax.swing.JButton small2pcBtn;
    private javax.swing.JButton smallPantbtn;
    private javax.swing.JButton smallShirtBtn;
    private javax.swing.JButton smallTieBtn;
    // End of variables declaration//GEN-END:variables
}
