/* Name: Harshita Aka Dharna Mistry
 * Name : Sheenam Kamal
 * Name : Kour Sanminder
 * JavaProject
 *
 * description:A java GUI application which gives an option to customer that 
 * if he wants to pay with cash or dabit or paylater.
 */

package javaproject;

import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class Payment extends javax.swing.JFrame {

    /**
     * Creates new form Payment
     */
    public Payment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        signInMenuItem = new javax.swing.JMenuItem();
        pickUpMenuItem = new javax.swing.JMenuItem();
        registerMenuItem = new javax.swing.JMenuItem();
        cashButton = new javax.swing.JButton();
        DebitButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        signInMenuItem1 = new javax.swing.JMenuItem();
        pickUpMenuItem1 = new javax.swing.JMenuItem();
        registerMeniItem = new javax.swing.JMenuItem();

        signInMenuItem.setText("Signin");
        signInMenuItem.setToolTipText("");

        pickUpMenuItem.setText("Pick Up");
        pickUpMenuItem.setToolTipText("");

        registerMenuItem.setText("Register");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(500, 500));
        setMinimumSize(new java.awt.Dimension(500, 500));
        setPreferredSize(new java.awt.Dimension(500, 500));
        setResizable(false);
        getContentPane().setLayout(null);

        cashButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cashButton.setForeground(new java.awt.Color(0, 204, 255));
        cashButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/_images/cashSymbol.jpg"))); // NOI18N
        cashButton.setText("Cash");
        cashButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cashButton);
        cashButton.setBounds(90, 180, 130, 70);

        DebitButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        DebitButton.setForeground(new java.awt.Color(0, 204, 255));
        DebitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/_images/debit.jpg"))); // NOI18N
        DebitButton.setText("Debit");
        DebitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DebitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(DebitButton);
        DebitButton.setBounds(270, 180, 140, 70);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 255));
        jLabel2.setText("Customer's Payment Method");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 130, 290, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 153));
        jLabel3.setText("ZOOM DRY CLEANING");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(130, 60, 199, 22);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 153, 153));
        jButton1.setText("Pay Later");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(180, 340, 120, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/_images/background.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(500, 500));
        jLabel1.setMinimumSize(new java.awt.Dimension(500, 500));
        jLabel1.setPreferredSize(new java.awt.Dimension(500, 500));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 500, 500);

        jMenu1.setText("Menu");

        signInMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/_images/signInsmall.jpg"))); // NOI18N
        signInMenuItem1.setText("Signin");
        signInMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(signInMenuItem1);

        pickUpMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/_images/pickUpSmall.jpg"))); // NOI18N
        pickUpMenuItem1.setText("Pick Up");
        pickUpMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pickUpMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(pickUpMenuItem1);

        registerMeniItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/_images/registerSmall.png"))); // NOI18N
        registerMeniItem.setText("Register");
        registerMeniItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerMeniItemActionPerformed(evt);
            }
        });
        jMenu1.add(registerMeniItem);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cashButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashButtonActionPerformed
        CashOption c = new CashOption();
        c.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cashButtonActionPerformed

    private void signInMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInMenuItem1ActionPerformed
        signIn s = new signIn();
        s.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_signInMenuItem1ActionPerformed

    private void pickUpMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pickUpMenuItem1ActionPerformed
        PickUp p = new PickUp();
        p.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_pickUpMenuItem1ActionPerformed

    private void registerMeniItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerMeniItemActionPerformed
        Register r = new Register();
        r.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_registerMeniItemActionPerformed

    private void DebitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DebitButtonActionPerformed
        JOptionPane.showMessageDialog(null, "Thank you come again :) ", "Greetings", JOptionPane.INFORMATION_MESSAGE);
        this.setVisible(false);
    }//GEN-LAST:event_DebitButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JOptionPane.showMessageDialog(null, "Thank you come again :) ", "Greetings", JOptionPane.INFORMATION_MESSAGE);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DebitButton;
    private javax.swing.JButton cashButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem pickUpMenuItem;
    private javax.swing.JMenuItem pickUpMenuItem1;
    private javax.swing.JMenuItem registerMeniItem;
    private javax.swing.JMenuItem registerMenuItem;
    private javax.swing.JMenuItem signInMenuItem;
    private javax.swing.JMenuItem signInMenuItem1;
    // End of variables declaration//GEN-END:variables
}
