/* Name: Harshita Aka Dharna Mistry
 * Name : Sheenam Kamal
 * Name : Kour Sanminder
 * JavaProject
 *
 * description:A java GUI application to create an order, register a person and
 * signin if person is already registered.
 */

package javaproject;

import javax.swing.JFrame;


public class WelcomePage extends javax.swing.JFrame {

    /**
     * Creates new form WelcomePage
     */
    public WelcomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        register = new javax.swing.JButton();
        signIn = new javax.swing.JButton();
        pickUp = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        signInMenu = new javax.swing.JMenuItem();
        pickUpMenu = new javax.swing.JMenuItem();
        RegisterMenu = new javax.swing.JMenuItem();

        jLabel1.setOpaque(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 500));
        setResizable(false);
        getContentPane().setLayout(null);

        register.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        register.setForeground(new java.awt.Color(0, 153, 153));
        register.setIcon(new javax.swing.ImageIcon(getClass().getResource("/_images/register.png"))); // NOI18N
        register.setText("Register");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });
        getContentPane().add(register);
        register.setBounds(140, 280, 163, 59);

        signIn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        signIn.setForeground(new java.awt.Color(0, 153, 153));
        signIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/_images/signIn.jpg"))); // NOI18N
        signIn.setText("Signin");
        signIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInActionPerformed(evt);
            }
        });
        getContentPane().add(signIn);
        signIn.setBounds(50, 160, 150, 57);

        pickUp.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pickUp.setForeground(new java.awt.Color(0, 153, 153));
        pickUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/_images/pickUp.jpg"))); // NOI18N
        pickUp.setText("Pick up");
        pickUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pickUpActionPerformed(evt);
            }
        });
        getContentPane().add(pickUp);
        pickUp.setBounds(290, 160, 150, 57);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 153));
        jLabel3.setText("ZOOM DRY CLEANING");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(160, 60, 199, 22);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/_images/background.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-10, -160, 560, 810);

        jMenu1.setText("Menu");

        signInMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/_images/signInsmall.jpg"))); // NOI18N
        signInMenu.setText("Signin");
        signInMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInMenuActionPerformed(evt);
            }
        });
        jMenu1.add(signInMenu);

        pickUpMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/_images/pickUpSmall.jpg"))); // NOI18N
        pickUpMenu.setText("Pick up");
        pickUpMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pickUpMenuActionPerformed(evt);
            }
        });
        jMenu1.add(pickUpMenu);

        RegisterMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/_images/registerSmall.png"))); // NOI18N
        RegisterMenu.setText("Register");
        RegisterMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterMenuActionPerformed(evt);
            }
        });
        jMenu1.add(RegisterMenu);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pickUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pickUpActionPerformed
        PickUp p = new PickUp();
        p.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_pickUpActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        Register r = new Register();
        r.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_registerActionPerformed

    private void signInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInActionPerformed
        signIn s = new signIn();
        s.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_signInActionPerformed

    private void signInMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInMenuActionPerformed
       signIn s = new signIn();
        s.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_signInMenuActionPerformed

    private void pickUpMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pickUpMenuActionPerformed
       PickUp p = new PickUp();
       p.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_pickUpMenuActionPerformed

    private void RegisterMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterMenuActionPerformed
        Register r = new Register();
        r.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_RegisterMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WelcomePage().setSize(200,200);
                new WelcomePage().setVisible(true);
            }
        });
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem RegisterMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton pickUp;
    private javax.swing.JMenuItem pickUpMenu;
    private javax.swing.JButton register;
    private javax.swing.JButton signIn;
    private javax.swing.JMenuItem signInMenu;
    // End of variables declaration//GEN-END:variables
}
